### ISSUE TITLE
Would love to see the context page

### ISSUE THREAD

**Issue by gilescope** [actix/book#10]
Please don't stop just when it was getting interesting! Really like the guild - hope you find a little time to push it forwards a little. - thankyou!

**Comment by gilescope** [comment]
btw, newbie fail: would be great to point out that an actor Result really needs to be of type Result<_,_>. It's obvious when you think of it, but when you have for example type Result = String you get some non-obvious error messages.

**Comment by vimpunk** [comment]
Seconded, it would be great to see this book finished.

**Comment by MrEmanuel** [comment]
I really love this book! It's such a great intro!
I would also love to see a similar thing for actix-web. I can't quite figure out how the actor model is relevant for actix-web. Might open a separate issue in that repo.

**Comment by SeedyROM** [comment]
> I really love this book! It's such a great intro!
> I would also love to see a similar thing for actix-web. I can't quite figure out how the actor model is relevant for actix-web. Might open a separate issue in that repo.

From my understanding actix-web is just a async http server implemented with actix, the code isn't the easiest to read but it's not anything special on top of the internal lib.

**Comment by fakeshadow** [comment]
actix-web is not built on top of actix. In actix-web's git repo only actix-web-actors crate depend on actix.
