### ISSUE TITLE
Addresses typo

### ISSUE THREAD

**Issue by TatriX** [actix/book#19]
[Here](https://actix.rs/book/actix/sec-3-address.html) it shows to exactly the same code snippets saying
> Same example, but returned address is thread safe and can be sent to different thread.

which is probably wrong.

**Comment by DoumanAsh** [comment]
Ah yes, it should be removed, I wasn't careful when renaming Addresses

**Comment by DoumanAsh** [comment]
Thanks, I updated the chapter
