### ISSUE TITLE
Update to 0.9/0.10-alpha

### ISSUE THREAD

**Issue by JohnTitor** [actix/book#44]
The current book is written with actix 0.7, it's quite old. We should rewrite this book with actix 0.9/0.10-alpha.

**Comment by JohnTitor** [comment]
cc @Jonathas-Conceicao for awareness.

**Comment by savekirk** [comment]
@JohnTitor thanks for the review of #47. I'll attempt documenting the other missing sections when `0.9-next` branch is merged to master.

**Comment by JohnTitor** [comment]
> I'll attempt documenting the other missing sections when 0.9-next branch is merged to master.

Thanks! I merged it via #48.
