### ISSUE TITLE
Replace/Update `Errors` example from `failure` to `thiserror`/`anyhow`

### ISSUE THREAD

**Issue by CinchBlue** [actix/book#52]
Hi,

[The `failure` crate is deprecated](https://github.com/rust-lang-nursery/failure/pull/347). We should try to update our examples to `thiserror`/`anyhow` since they are now considered more "idiomatic."

I'd be willing to do the legwork, but I need to have someone validate the example I would write.

Thanks.

**Comment by JohnTitor** [comment]
AFAIK this repository doesn't contain any example with `failure` crate. Do you mean actix/examples repo? Then yes, we could replace it with the alternative crate such as `thiserror`/`anyhow`. Anyway, I'm going to close this issue as we shouldn't track this here.
